linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      # - <<: *linux
      #   env: GCC_VERSIONS=8 DOCKER_IMAGE=lasote/conangcc8 ARCHS=x86_64
      - <<: *linux
        env: CLANG_VERSIONS=6.0 DOCKER_IMAGE=lasote/conanclang60 ARCHS=x86_64 RUNNER=runner-${GCC_VERSIONS}${CLANG_VERSIONS}-${ARCHS}

before_install:
  - docker pull ${DOCKER_IMAGE}
  - docker run -e GCC_VERSIONS -e CLANG_VERSIONS -u root -d --name "${RUNNER}" -v ${PWD}:${PWD} -w ${PWD} --rm -t ${DOCKER_IMAGE}

install:
  - chmod +x .ci/install.sh
  - docker exec "${RUNNER}" /bin/bash ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - docker exec "${RUNNER}" /bin/bash ./.ci/run.sh
  - docker stop "${RUNNER}"