linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
osx: &windows
   os: windows
   language: cpp
matrix:
   include:
      - <<: *linux
        env: CXX_VERSION=8 DOCKER_IMAGE=lasote/conangcc8 ARCHS=x86_64
      - <<: *linux
        env: CXX_VERSION=6.0 DOCKER_IMAGE=lasote/conanclang60 ARCHS=x86_64

install:
  - export RUNNER="runner-${CXX_VERSION}-${RANDOM}"
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh