linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64

before_install:
  - docker pull ${CONAN_DOCKER_IMAGE}
  - docker run -u root -d --name runner-${CONAN_GCC_VERSIONS}-${CONAN_ARCHS} -v ${PWD}:${PWD} -w ${PWD} --rm -t ${CONAN_DOCKER_IMAGE}
  - docker ps -a

install:
  - docker ps -a
  - chmod +x .ci/install.sh
  - docker exec runner-${CONAN_GCC_VERSIONS}-${CONAN_ARCHS} /bin/bash -c "ls -la; /bin/bash ./.ci/install.sh;"

script:
  - docker ps -a
  - chmod +x .ci/run.sh
  - docker exec runner-${CONAN_GCC_VERSIONS}-${CONAN_ARCHS} /bin/bash -c "ls -la;/bin/bash ./.ci/run.sh;"
  - docker stop runner-${CONAN_GCC_VERSIONS}-${CONAN_ARCHS}