linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
osx: &windows
   os: windows
   language: cpp
matrix:
   include:
      - <<: *linux
        env: CXX_VERSION=gcc8 DOCKER_IMAGE=lasote/conangcc8 ARCHS=x86_64 MY_OS=linux
      - <<: *linux
        env: CXX_VERSION=clang-6.0 DOCKER_IMAGE=lasote/conanclang60 ARCHS=x86_64 MY_OS=linux
      - <<: *osx
        osx_image: xcode10
        env: CXX_VERSION=apple-clang-10.0 MY_OS=osx
      - <<: *windows
        env: CXX_VERSION=vs2017 MY_OS=windows


install:
  - export RUNNER="runner-${CXX_VERSION}-${RANDOM}"
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh